export const REQ_BOOKINGS_DATA = "REQ_BOOKINGS_DATA"
export const GET_BOOKINGS_DATA_SUCCESS = "GET_BOOKINGS_DATA_SUCCESS"
export const REQ_BOOKINGS_DATA_FAIL = "REQ_BOOKINGS_DATA_FAIL"




export const REQ_CONFIRM_BOOKING = "REQ_CONFIRM_BOOKING"
export const BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
export const BOOKING_CONFIRMATION_FAILED = "BOOKING_CONFIRMATION_FAILED"
